### ISSUE TITLE
Course serializer does not handle empty category names or weights

### ISSUE THREAD

**Issue by joshcosta** [gradebook/utils#54]
![image](https://user-images.githubusercontent.com/43763502/85648743-16492300-b667-11ea-859e-c91be1daaa86.png)

**Comment by vikaspotluri123** [comment]
How do you think the serialization should happen? Should we allow courses w/ empty categories / weights to be shared since they're incomplete?

**Comment by joshcosta** [comment]
We can allow them to be shared but if a row is truly empty we should drop it from the export. If they include a name or weight I think it needs to make it into the template

**Comment by joshcosta** [comment]
Once course warnings is implemented with the new gradetable we can prevent creating templates when the course is in a bad state.


https://github.com/gradebook/client/issues/5

**Comment by vikaspotluri123** [comment]
> If they include a name or weight I think it needs to make it into the template

I guess my issue with this is if it's not filled out, the template isn't as usable 😕 

I think the main action item for this issue is

 - Course Serializer should remove empty categories during the serialization process

Everything else should be handled in a different repository?

**Comment by vikaspotluri123** [comment]
@joshcosta do you think we need to do anything on client? I don't think there will be many courses that were impacted by this, and the new ones won't be an issue

**Comment by joshcosta** [comment]
Yes I think before creating the template a user needs to be warned somehow if rows are being removed that had a name or weight. The completely empty rows are a non-issue

**Comment by vikaspotluri123** [comment]
Ok, I'm going to leave this issue open in that case, since we're going to need to release a minor that adds metadata with that info
