### ISSUE TITLE
Pluralizer doesn't handle `bonus` properly

### ISSUE THREAD

**Issue by vikaspotluri123** [gradebook/utils#65]
`Bonu` is not valid :wink:

**Comment by vikaspotluri123** [comment]
@joshcosta or @ramsays what rule can we use for this? I can't think of one since `menus` and `bonus` conflict with each other. Do we just want to add an explicit override list?

**Comment by joshcosta** [comment]
Here's a nice [resource](https://www.litscape.com/word_tools/ends_with.php) for finding words with the same ending

**Comment by joshcosta** [comment]
Yes I think we have to explicitly override in this case
